name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: [ '3.1', '3.2' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run checks
        env:
          RE_RECORD_VCR: ${{ vars.RE_RECORD_VCR }}
          LIT_WORLDCAT_API_KEY: ${{ secrets.LIT_WORLDCAT_API_KEY }}
          LIT_WORLDCAT_API_SECRET: ${{ secrets.LIT_WORLDCAT_API_SECRET }}
        run: bundle exec rake

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/**
